# Generated by Django 4.1.9 on 2023-07-16 18:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True, help_text='Oluşturulma')),
                ('modified_on', models.DateTimeField(auto_now=True, help_text='Güncelleme')),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(blank=True, max_length=150, null=True)),
                ('description', models.CharField(max_length=250)),
                ('created_by', models.ForeignKey(editable=False, help_text='Oluşturan', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_cby', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(editable=False, help_text='Güncelleyen', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_mby', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'brand_products',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True, help_text='Oluşturulma')),
                ('modified_on', models.DateTimeField(auto_now=True, help_text='Güncelleme')),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=50)),
                ('category_code', models.CharField(db_index=True, max_length=50, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(default='', upload_to='category')),
                ('created_by', models.ForeignKey(editable=False, help_text='Oluşturan', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_cby', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(editable=False, help_text='Güncelleyen', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_mby', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'categories',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True, help_text='Oluşturulma')),
                ('modified_on', models.DateTimeField(auto_now=True, help_text='Güncelleme')),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=255)),
                ('weight', models.IntegerField(blank=True, null=True)),
                ('product_code', models.CharField(db_index=True, max_length=50, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(default='', upload_to='products')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='brand_products', to='app.brand')),
                ('categories', models.ManyToManyField(related_name='products_category', to='app.category')),
                ('created_by', models.ForeignKey(editable=False, help_text='Oluşturan', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_cby', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'products',
            },
        ),
        migrations.CreateModel(
            name='RentalPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True, help_text='Oluşturulma')),
                ('modified_on', models.DateTimeField(auto_now=True, help_text='Güncelleme')),
                ('is_active', models.BooleanField(default=True)),
                ('rental_type', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('yearly', 'Yearly')], max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('created_by', models.ForeignKey(editable=False, help_text='Oluşturan', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_cby', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(editable=False, help_text='Güncelleyen', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_mby', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Rental',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True, help_text='Oluşturulma')),
                ('modified_on', models.DateTimeField(auto_now=True, help_text='Güncelleme')),
                ('is_active', models.BooleanField(default=True)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('is_completed', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(editable=False, help_text='Oluşturan', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_cby', to=settings.AUTH_USER_MODEL)),
                ('drone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.product')),
                ('modified_by', models.ForeignKey(editable=False, help_text='Güncelleyen', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_mby', to=settings.AUTH_USER_MODEL)),
                ('rental_period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.rentalperiod')),
                ('renter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProductModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True, help_text='Oluşturulma')),
                ('modified_on', models.DateTimeField(auto_now=True, help_text='Güncelleme')),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(blank=True, max_length=150, null=True)),
                ('description', models.CharField(max_length=250)),
                ('created_by', models.ForeignKey(editable=False, help_text='Oluşturan', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_cby', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(editable=False, help_text='Güncelleyen', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_mby', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'product_models',
            },
        ),
        migrations.AddField(
            model_name='product',
            name='model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_models', to='app.productmodel'),
        ),
        migrations.AddField(
            model_name='product',
            name='modified_by',
            field=models.ForeignKey(editable=False, help_text='Güncelleyen', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_mby', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='product',
            name='rental_periods',
            field=models.ManyToManyField(related_name='products_period', to='app.rentalperiod'),
        ),
    ]
