# Generated by Django 4.1.9 on 2023-07-16 20:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rental',
            old_name='drone',
            new_name='product',
        ),
    ]
