# Generated by Django 4.1.9 on 2023-07-17 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rename_drone_rental_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='rental',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
